### ISSUE TITLE
Rohan here : Your Expertise in making Virtual Try On is required 

### ISSUE THREAD

**Issue by 24thTinyGiant** [practice404/clothes-virtual-try-on#5]
hello @practice404  🙌 myself Rohan I contacted you on facebook regarding how to make a image based virtual try on ,I just want to know which sources you referred to make this amazing project I also wanted to make one for my college project like how did write the code required the code  to transfer clothes and human body segmentation .Please Help ,You help is Required  🙏🙏

**Comment by practice404** [comment]
@24thTinyGiant Please refer to [C_A_MARK_2.ipynb](https://github.com/practice404/clothes-virtual-try-on/blob/main/C_A_MARK_2.ipynb) notebook and [run.py](https://github.com/practice404/clothes-virtual-try-on/blob/main/run.py) file and follow their logical flow for better understanding. We also attached a PowerPoint, you can refer to that too
