### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000018500461AD0>

### ISSUE THREAD

**Issue by 24thTinyGiant** [practice404/clothes-virtual-try-on#6]
I'm getting this error and i followed all the steps mentioned in the repo first i applied for the API key at ngork and the changes the API key to my API key in in remove bg then also I'm getting this error  can you or any one help me please 🙏🥺 @practice404

**Comment by punithan328** [comment]
I'm also getting same error can u help me and give solution
